[tool.poetry]
name = "neurobench"
version = "0.1.0"
description = "Collaborative, Fair, and Representative Benchmarks for Neuromorphic Computing"
authors = ["NeuroBench Team <neurobench@googlegroups.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24.3"
torch = "^2.0.1"
torchaudio = "^2.0.2"
tqdm = "^4.65.0"
snntorch = {version = "^0.6.4", optional = true}
speech2spikes = {version = "^1.0.0", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-cov = "^4.1.0"

[tool.poetry.extras]
snntorch = ["snntorch"]
speech2spikes = ["speech2spikes"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
